# Generated by Django 4.1.6 on 2023-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombreCategoria', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='consola',
            fields=[
                ('idConsola', models.AutoField(primary_key=True, serialize=False)),
                ('nomConsola', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='figura',
            fields=[
                ('idFigura', models.AutoField(primary_key=True, serialize=False)),
                ('nomFigura', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='idmarca',
            fields=[
                ('nomMarca', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='juego',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nomjuego', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
