# Generated by Django 4.2.1 on 2023-06-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Mantic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nomMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='idmarca',
        ),
        migrations.AddField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='consolapictures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='juegopictures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='consola',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_Mantic.marca'),
            preserve_default=False,
        ),
    ]
