# Generated by Django 4.2.1 on 2023-06-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Mantic', '0002_marca_delete_idmarca_consola_imagen_juego_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombreCategoria',
            new_name='idcategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombrecategoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figura',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='figurapictures/%Y/%m/%d/'),
        ),
    ]
