# Generated by Django 4.2.1 on 2023-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Mantic', '0004_alter_consola_imagen_alter_figura_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='consolapictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='figurapictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='juegopictures/%Y/%m/%d/'),
        ),
    ]
