# Generated by Django 4.2.1 on 2023-06-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Mantic', '0005_alter_consola_imagen_alter_figura_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='nventas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figura',
            name='nventas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='nventas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
